#!/bin/bash -x

# Add services
chkconfig --add postfix

# Most systems default to runlevel 3
chkconfig --level 3 postfix on 
chkconfig --level 3 psacct on
chkconfig --level 3 smartd off
chkconfig --level 3 anacron off
chkconfig --level 3 auditd off
chkconfig --level 3 irqbalance off
chkconfig --level 3 mdmpd off
chkconfig --level 3 portmap off
chkconfig --level 3 nfslock off
chkconfig --level 3 sendmail off
chkconfig --level 3 cpuspeed off
chkconfig --level 3 autofs off
chkconfig --level 3 rpcidmapd off
chkconfig --level 3 rpcsvcgssd off
chkconfig --level 3 rpcgssd off
chkconfig --level 3 pcscd off
chkconfig --level 3 gpm off
chkconfig --level 3 hidd off
chkconfig --level 3 yum-updatesd off

# EC2 defaults to runlevel 4 -- why?
chkconfig --level 4 postfix on 
chkconfig --level 4 psacct on
chkconfig --level 4 smartd off
chkconfig --level 4 anacron off
chkconfig --level 4 auditd off
chkconfig --level 4 irqbalance off
chkconfig --level 4 mdmpd off
chkconfig --level 4 portmap off
chkconfig --level 4 nfslock off
chkconfig --level 4 sendmail off
chkconfig --level 4 cpuspeed off
chkconfig --level 4 autofs off
chkconfig --level 4 rpcidmapd off
chkconfig --level 4 rpcsvcgssd off
chkconfig --level 4 rpcgssd off
chkconfig --level 4 pcscd off
chkconfig --level 4 gpm off
chkconfig --level 4 hidd off
chkconfig --level 4 yum-updatesd off

# Delete services
chkconfig --del auditd
chkconfig --del irqbalance
chkconfig --del mdmpd
chkconfig --del NetworkManager
chkconfig --del dund
chkconfig --del firstboot
chkconfig --del irda
chkconfig --del smartd
chkconfig --del kudzu
chkconfig --del hidd
chkconfig --del gpm
chkconfig --del pcscd
chkconfig --del cpuspeed
chkconfig --del rdisc
chkconfig --del sendmail
chkconfig --del readahead_later
chkconfig --del wpa_supplicant
chkconfig --del pand
chkconfig --del netplugd
chkconfig --del cups
chkconfig --del avahi-daemon
chkconfig --del avahi-dnsconfd

#CentOS 5.2 does not support all these pacakges, to compensate exit with 0 for now
#TODO: add conditionals for dist
exit 0
