require 'rubygems'
gem 'dm-core', '~> 0.10.2'

require File.join(File.dirname(__FILE__), "lib", "storage")

desc "Perform automigration"
task :automigrate do
  ::DataMapper.auto_migrate!
end

desc "Perform non destructive automigration"
task :autoupgrade do
  ::DataMapper.auto_upgrade!
end
