source "https://rubygems.org"

gem "rake"

gem "mime-types", "~> 1.0"

gem "right_api_objects", :git => "git@github.com:rightscale/right_api_objects.git", :tag => "v0.1.1"

gem "ruby-debug"

gem "virtualmonkey",
  :git => "git@github.com:rightscale/virtualmonkey.git",
  :branch => "release2.5"

