name             "rightimage_image_virtualbox"
maintainer       "RightScale, Inc."
maintainer_email "support@rightscale.com"
description      "Image provider cookbook for building RightImage vagrant boxes"
version          "14.0.0"
license          "Apache v2.0"
